### PR TITLE
Add ponies

### PR DESCRIPTION
**Pull request by Tadaboody**
I know that these aren't anime girls but really, isn't Twilight an anime
girl at heart? Aren't we all?

### CODE REVIEW

**Comment by Melon-Bread** [comment]
=|

**Comment by Tadaboody** [comment]
=)

**Comment by Hoi15A** [comment]
Ehhh idek if that really fits well into this repo. Maybe if it were called Ponies holding programming books, but this feels a bit out of place here imo

**Comment by fuerbringer** [comment]
# No

**Comment by joojoku** [comment]
Perhaps the ponies could be moved to the Other folder?

**Comment by Melon-Bread** [comment]
Why not just make a pony repo?

**Comment by MeyerHallot** [comment]
I'm sorry but this is strictly an anime repo. Nothing against ponies this just isn't the right place for them.

**Pull request closed without merging**
